### PR TITLE
[cmake] PopSift_DIR case sensitive

### PR DESCRIPTION
**Pull request by griwodz**
PopSift project name is CamelCase in develop and feature_repeatability branches. find_package(Popsift) failed, changed to find_package(PopSift).

### CODE REVIEW

**Comment by simogasp** [comment]
Actually all the cmake part must be adjusted as we switched to modern cmake for popsift but the `popsift` branch is not up-to-date with it

**Comment by griwodz** [comment]
Is the cmake update in progress? Otherwise, we could allow this patch anyway.

**Comment by simogasp** [comment]
no I don't think so, this branch is not mergeable at the moment and needs to be cleaned a lot

**Comment by fabiencastan** [comment]
I have started to squash the "popsift" and clean it... but it's not yet pushed.

**Comment by griwodz** [comment]
OK, I've made equivalent changes on top of popart_squash.

**Pull request closed without merging**
